### ISSUE TITLE
error npm in getting started??

### ISSUE THREAD

**Issue by prasetion** [iBicha/youtube-dl-server#1]
Hey @iBicha , great support from you, and thank you for the time. Well, because YouTube always update, and we don't want to always rebuild the game because the plugin should be updated, we try to migrate the way using YouTube-dl-server like your said before, but when I try npm install, there is error

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! youtube-dl-server@1.0.0 postinstall: `mkdir -p tools/bin && wget https://yt-dl.org/downloads/latest/youtube-dl -O tools/bin/youtube-dl && chmod a+rx tools/bin/youtube-dl`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the youtube-dl-server@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by iBicha** [comment]
Hm, I need to see more logs, but I'm going to get that this is probably because you don't have wget on the machine.
Which OS? Can you provide the logs file that was created by npm? Also, can you run `wget --version` in command line, and post the output?

**Comment by iBicha** [comment]
#2 should address this issue.

**Comment by iBicha** [comment]
Closing. Please reopen issue if #2 does not fix the issue.
