### ISSUE TITLE
question about bandwidth

### ISSUE THREAD

**Issue by tleylan** [iBicha/youtube-dl-server#11]
Hi there I've cloned the project and I'm happy to say it works :-) I'd like to get a little information about the bandwidth requirements so I can select my best option for hosting.

First, is the site serving the entire video (I suspect that it is). I was hoping that it could translate the URL into something that could be served by the YouTube servers.

And if so, does that mean additional connections will download their own copies as well? I believe it doesn't stream the video (correct me if I'm wrong). Thanks.

**Comment by iBicha** [comment]
This project only uses yt-dlp to parse YouTube web page and find the metadata of the video (such as the url). It doesn't stream the video itself, so it is freed quickly.

You should probably start with a small machine, and scale horizontally if you have lots of traffic.

**Comment by tleylan** [comment]
Ah that was my hope, thanks. I didn't read through all the code but will eventually. I have a somewhat bad habit of refactoring code which gives me a lot of insight into how it works. I have a virtual server at my disposal but I toyed with making a spare machine I have available on the Internet as well.

**Comment by iBicha** [comment]
Glad this is what you're looking for! Feel free to close this issue if this answers your question
