### ISSUE TITLE
I'm not understanding the response

### ISSUE THREAD

**Issue by tleylan** [iBicha/youtube-dl-server#12]
Hi again, sorry I'm trying to work out the kinks as quickly as possible. I have the service running and using Postman I make a GET watch request. I get a response but it isn't just a URL that I can use to view the video.

The details from my test are listed below. Am I making an obvious mistake?

Thanks.

https://rr2---sn-q4flrnld.googlevideo.com/videoplayback?expire=1676507712&ei=3yXtY4eyPL2Cir4P74u90Ac&ip=199.119.163.186&id=o-AC8jY4qMObrcVJHWmtXYbDtVSEQE4ppvKh38EjAbDwpk&itag=22&source=youtube&requiressl=yes&mh=1R&mm=31%2C26&mn=sn-q4flrnld%2Csn-5ualdnz7&ms=au%2Conr&mv=u&mvi=2&pl=22&spc=H3gIhiNqsmwX2SrZPyYbGhoy4pHgCV8&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=148.166&lmt=1667621245853676&mt=1676485211&fvip=2&fexp=24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJLhA6OePgITw1t54jHXv594VsMAOqPqsUXdgnAhsCXxAiEA40QP5pdGvni2Gk7ZFWEHOmgvzDRjAiHrUwuF2ffdEJY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIhAO3vCaiEp_Haxa0b2sOFGamShhcb4ybkSG2BsITO_McEAiBnfkfYbjfEY_uu3Nj06O1rJYRjZPv5SghPNjoTLABAsw%3D%3D

**Comment by iBicha** [comment]
As mentioned in https://github.com/iBicha/youtube-dl-server#api
> GET /watch  Redirects to the raw video url.

It means if you open the url in the browser (or a video player) it will redirect to the raw video url, the video will play.

If you don't want that, use `GET /v1/video` which will return a json payload you can parse

**Comment by tleylan** [comment]
Will do, thanks again. I knew it was in there somewhere :-)
