### ISSUE TITLE
a heads up there is a pending bug fix in yt-dlp 

### ISSUE THREAD

**Issue by tleylan** [iBicha/youtube-dl-server#14]
Something apparently changed at YouTube... I'm getting the error discussed here as well.

https://github.com/yt-dlp/yt-dlp/issues/6251

I'll probably have to wait until the master branch is released. Your download.js function can get it for me but I wouldn't know what to change to get a compiled version of the master branch. Bummer.

**Comment by iBicha** [comment]
Thanks, youtube-dl-server does not need to manager yt-dlp releases, it will download the latest on install
use `npm i` command to do that once the new release is out.

**Comment by tleylan** [comment]
will do... talk about timing :-)
