### ISSUE TITLE
Unable to extract uploader ID

### ISSUE THREAD

**Issue by xkozma** [iBicha/youtube-dl-server#15]
Hello, I have been using this package and it worked smoothly till today - now it states

 {"error":"Command failed: /app/tools/bin/youtube-dl -f \"best\" --dump-single-json --no-warnings https://www.youtube.com/watch?v=b1vTbYMN3EU\nERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n","stderr":"ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.\n","stdout":""}

Any idea what to do with it? Seen some python related workaround on the yt dl repo but dont know how to apply it here. It worked today, just used the app as usual, changed nothing, but this appeared, have it hosted on heroku.

Thank you

**Comment by iBicha** [comment]
A yt-dlp release was done 11 hours ago, it should address this.
You can run `npm i` or `node ./tools/download.js` to get the latest yt-dlp

**Comment by xkozma** [comment]
Tried "npm i" already, downloaded the 1.2.2 version, but didnt help, so I guess, I just need to wait?

**Comment by iBicha** [comment]
I ran the server locally, and tried 
```
http://localhost:8080/watch?v=https://www.youtube.com/watch?v=b1vTbYMN3EU&cli=yt-dlp
```
This showed me the exact error you showed me. Run `npm i` again, it will retrigger fetching both tools.
I ran 
```
http://localhost:8080/watch?v=https://www.youtube.com/watch?v=b1vTbYMN3EU&cli=yt-dlp
```
again, and then it worked.

**Comment by xkozma** [comment]
I needed to redeploy the app, then update, now everything works, thank you for quick and useful response :)
