### ISSUE TITLE
I get an odd response

### ISSUE THREAD

**Issue by tleylan** [iBicha/youtube-dl-server#18]
I am hoping that you just have some idea where I could look. I have dev and prod copies of my service. They have the identical code base (and youtube dlls).

using dev:  http://localhost:3004/watch?v=d9MyW72ELq0&cli=yt-dlp will return the actual video. The service returns a redirect (as you know) for watch.

using prod: an error is thrown with Cannot GET /videoplayback as the message.

I just can't see the difference other than prod uses https but it is doing that for all the rest endpoints that work.

**Comment by tleylan** [comment]
It came to me last night. I believe it is CORS-related. Oops, but that wouldn't explain why the redirect is there already. If it didn't work it wouldn't be the response to for watch. Maybe a setting?

**Comment by tleylan** [comment]
the following is the response locally. I see \videoplayback in the URL of course but again it works differently locally vs production. I changed my IP address.

`https://rr2---sn-ab5l6nrr.googlevideo.com/videoplayback?expire=1679079724&ei=zGQUZOvgE8rhigSq4LmIAg&ip=42.219.215.116&id=o-AMIL_zkaycLyfZZg0pT0G2gpdlgP09KbzJrKiVdiUD43&itag=22&source=youtube&requiressl=yes&mh=1R&mm=31%2C26&mn=sn-ab5l6nrr%2Csn-p5qlsn76&ms=au%2Conr&mv=m&mvi=2&pl=15&initcwndbps=1202500&spc=H3gIhmrypiiSfcd_SObf7ucBY3aZRzg&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=148.166&lmt=1667621245853676&mt=1679057830&fvip=3&fexp=24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgZOpT8g2ez-UMgGCFCbWN3DlTFvtlhSiB0HQQjfDcqWYCIQCk-DVSXtS5vUplV7hEOYkte31_yQOqYMqksdTspKymYQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJnE69XCzWO2WSxiYzvJgcdG5txigf1nhoZPgD2hR2TkAiEA0VUkHs4h4yD0BBbJXCpurUa5XlgNy9CV347_-577ojI%3D`

**Comment by tleylan** [comment]
I checked whether CORS was getting in the way. I wasn't able to determine that. One extra clue might be that I'm hosting the website in IIS. It is just a pass-through site there is no code except for the Node backend. I have several sites set up that way but this is the only one I've attempted a redirect with.

It may be worthwhile for me to attempt a redirect from one of the others as a test. I was hoping it was a simple issue. The inclusion of the /videoplayback part of the path seems particularly odd but again it works on localhost perfectly fine. Not hosted in IIS there though.

**Comment by iBicha** [comment]
[CORS should not be the issue](https://github.com/iBicha/youtube-dl-server/blob/c0d8e8b4920c1ca3910637de43fc8860634c13b8/src/app.ts#L13) 
It's possible for youtube to block certain videos, if the server and client are different (detects ip address)
This is especially true if a video is only available to the country where the server is, and not where the client is

**Comment by tleylan** [comment]
Thanks. I really appreciate any info you have as it makes no sense to me after numerous test variations. The system works when I fetch the url both as JSON and as a string using another service endpoint.

I am pretty certain it isn't video-related as both my localhost and my server are in the U.S. and in both cases I'm using Postman to make issue the GET. It could be that the embedded IP address (that of my server) is obviously not the one that Postman is using but if that is the case...

I have to wonder how any service and use the watch endpoint. Wouldn't any server making the request be different than the client that made the call to the server?

Somehow I need to crack this but it could mean that I need a video streamer on my server. That would be bad.

**Comment by tleylan** [comment]
I've concluded that it is/was an issue with IIS. Something I just don't have set up correctly but I found a workaround. Thanks.
