### ISSUE TITLE
Huge CPU ussage

### ISSUE THREAD

**Issue by steam3d** [iBicha/youtube-dl-server#19]
I tested on virtual machine (1CPU 3.2GHz i5-1135G7). One request the direct URL take 30% CPU usage for 2-3 sec.
Is there way to reduce it?

**Comment by iBicha** [comment]
youtube-dl-server is pretty lightweight, but the heavy lifting is being done by yt-dlp cli.
We call the cli like so [here](https://github.com/iBicha/youtube-dl-server/blob/c0d8e8b4920c1ca3910637de43fc8860634c13b8/src/YoutubeDl.ts#LL15C28-L15C31)
If you can reproduce the same issue by calling the yt-dlp commandline, then maybe it's worth opening an issue in https://github.com/yt-dlp/yt-dlp/issues
