### ISSUE TITLE
url with leading hyphen or underscore fail

### ISSUE THREAD

**Issue by tleylan** [iBicha/youtube-dl-server#21]
I've got everything working finally (other issues were mine) BUT some YouTube ids begin with an underscore or hyphen. Both of these fail for me. It seems to get confused where the options end.

```
{
    "error": "Command failed: C:\\nodeApps\\videoApi\\tools\\bin\\yt-dlp.exe -f \"best\" --dump-single-json --no-warnings -i9Mqo99fKE\n\r\nUsage: yt-dlp.exe [OPTIONS] URL [URL...]\r\n\r\nyt-dlp.exe: error: no such option: -9\r\n",
    "stderr": "\r\nUsage: yt-dlp.exe [OPTIONS] URL [URL...]\r\n\r\nyt-dlp.exe: error: no such option: -9\r\n",
    "stdout": ""
}
```
a yt-dlp project mentions a way around it: _e.g. yt-dlp -- -QxK8NvFbaU_ but we are just calling the library so I don't know how to format it in such a case or if it is supported in this version.

**Comment by iBicha** [comment]
It's way simpler to pass the whole url (`https://www.youtube.com/watch?v=-QxK8NvFbaU`) but I agree the server should do some input sanitation

**Comment by tleylan** [comment]
I am passing the whole url in BTW. It worked except for 2 cases. One was the leading hyphen which you've fixed (thanks) and one had a leading underscore. I suspect the leading underscore is still a problem.

**Comment by iBicha** [comment]
Do you have an example that starts with underscore?

**Comment by tleylan** [comment]
Yes... https://www.youtube.com/watch?v=_jaGPxHMX1I

I confirmed that it didn't work and adjusted it as follows:

```
        if ((url.startsWith("-") || url.startsWith("_")) && !url.startsWith("-- ")) {
            url = "-- " + url;
        }

```

Thanks again for all your hard work.

**Comment by iBicha** [comment]
Without any additional checks, when I open http://localhost:8080/watch?v=_jaGPxHMX1I in the browser, it works fine
What errors are you seeing?

**Comment by tleylan** [comment]
Oh m'gosh. I am using Postman and the error was re: the response being too large. I increased that and now the underscore url isn't an issue. Fooled myself on that one.
