### ISSUE TITLE
Build on Heroku fails

### ISSUE THREAD

**Issue by markdimi** [iBicha/youtube-dl-server#5]
Hello. Kudos on your efforts.

Due to availability issues I would love to have an independent instance of the youtube server. However the heroku deploy returns and error and halts.

The error output is:

`-----> Building on the Heroku-20 stack

-----> Determining which buildpack to use for this app

-----> Node.js app detected

       

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NODE_VERBOSE=false

       NODE_ENV=production

       NODE_MODULES_CACHE=true

       

-----> Installing binaries

       engines.node (package.json):  unspecified

       engines.npm (package.json):   unspecified (use default)

       

       Resolving node version 14.x...

       Downloading and installing node 14.16.0...

       Using default npm version: 6.14.11

       

-----> Installing dependencies

       Installing node modules

       

       > youtube-dl-server@1.0.0 postinstall /tmp/build_bf68ee68

       > npm run download

       

       

       > youtube-dl-server@1.0.0 download /tmp/build_bf68ee68

       > node ./tools/download.js

       

       /tmp/build_bf68ee68/tools/download.js:17

               throw err;

               ^

       

       Error: connect ECONNREFUSED 95.143.172.170:443

           at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {

         errno: -111,

         code: 'ECONNREFUSED',

         syscall: 'connect',

         address: '95.143.172.170',

         port: 443

       }

       npm ERR! code ELIFECYCLE

       npm ERR! errno 1

       npm ERR! youtube-dl-server@1.0.0 download: `node ./tools/download.js`

       npm ERR! Exit status 1

       npm ERR! 

       npm ERR! Failed at the youtube-dl-server@1.0.0 download script.

       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

       

       npm ERR! A complete log of this run can be found in:

       npm ERR!     /tmp/npmcache.BgO0d/_logs/2021-03-26T12_40_09_496Z-debug.log

       npm ERR! code ELIFECYCLE

       npm ERR! errno 1

       npm ERR! youtube-dl-server@1.0.0 postinstall: `npm run download`

       npm ERR! Exit status 1

       npm ERR! 

       npm ERR! Failed at the youtube-dl-server@1.0.0 postinstall script.

       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

       

       npm ERR! A complete log of this run can be found in:

       npm ERR!     /tmp/npmcache.BgO0d/_logs/2021-03-26T12_40_09_538Z-debug.log

-----> Build failed

       

       We're sorry this build is failing! You can troubleshoot common issues here:

       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       

       Some possible problems:

       

       - Node version not specified in package.json

         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

       

       Love,

       Heroku

       

 !     Push rejected, failed to compile Node.js app.

 !     Push failed

`

(sorry for the formatting)

**Comment by iBicha** [comment]
Server downloads youtube-dl on install. Seems like https://yt-dl.org/ is down...

**Comment by markdimi** [comment]
Oh damn. Is that why your instance of the server is down? 
https://unity-youtube-dl-server.herokuapp.com/v1/video?url=https://www.youtube.com/watch?v=1PuGuqpHQGo

**Comment by iBicha** [comment]
The instance itself is not down, and is working fine. It's just returning `429 too many requests` because it's having traffic.
This is a youtube thing (they don't expect that many views from the same machine) => there are workarounds (cookies, etc) but I have not implemented something like that in this project.

**Comment by markdimi** [comment]
I see. I suppose I will have to wait for youtube-dl to be back up. 
Thanks for the help.

**Comment by iBicha** [comment]
Looks like things are back to normal. Closing
