### ISSUE TITLE
Updating heroku app

### ISSUE THREAD

**Issue by ubergeekseven** [iBicha/youtube-dl-server#9]
I think I found my issue with my setup used within unity. I have commented several times within the unity player git and I might have stumbled on my real issue.

I checked my heroku setup and it was running still. I then sent a request via the web to my app and got a returned Cannot GET /watch error on the page with a video I copied the video url  after the =. I then tried your link from the youtube-dl-server page and it worked directly from your heroku app. So, I pasted the same info into my web request. same Cannot GET /watch error.

I then clciked your super easy to deply app button and generated a new app with a different name. Copied your example url info into my new app web request and boom, it worked.

So, I have no experience with heoku other than your super simple button. Is there a method of pulling in updated data from your repository from the cli in heroku? I would like to be able to keep my same app address and your app is still functioning correctly.

If there is a method of pulling in the changes time to time, could you put that info into the readme for reference? I am now going to see what happens with my unity app and if I can pull in videos again without having to externally download them before trying to play from a network file. Having the ability to do it on the fly is much more user friendly for my users.

thanks for all the work put into this. it is great and I need to go learn more about heroku...

**Comment by iBicha** [comment]
Added a global install option, as well as docker, so that should do for anyone
